"""Backend protocol — every task backend must implement this interface."""

from __future__ import annotations

from typing import Protocol

from taskmanager.models import Comment, Document, Issue, Label, Project, ProjectLink, Status, Team, User


class TaskBackend(Protocol):
    """Protocol that all task-management backends must satisfy."""

    # Teams
    def list_teams(self) -> list[Team]: ...
    def get_user(self, query: str) -> User: ...

    # Statuses
    def list_statuses(self, team_id: str) -> list[Status]: ...
    def create_status(self, team_id: str, name: str, type: str, color: str) -> Status: ...

    # Labels
    def list_issue_labels(self) -> list[Label]: ...
    def create_issue_label(self, name: str, color: str) -> Label: ...
    def list_project_labels(self) -> list[Label]: ...
    def create_project_label(self, name: str, color: str, description: str = "") -> Label: ...

    # Projects
    def list_projects(self, label: str | None = None) -> list[Project]: ...
    def save_project(self, name: str, team: str, description: str = "", labels: list[str] | None = None) -> Project: ...
    def get_project_links(self, project_id: str) -> list[ProjectLink]: ...
    def create_project_link(self, project_id: str, label: str, url: str) -> ProjectLink: ...

    # Issues
    def list_issues(self, status: str | None = None, project: str | None = None) -> list[Issue]: ...
    def get_issue(self, issue_id: str, include_relations: bool = False) -> Issue: ...
    def save_issue(
        self,
        *,
        id: str | None = None,
        title: str | None = None,
        team: str | None = None,
        state: str | None = None,
        labels: list[str] | None = None,
        priority: int | None = None,
        description: str | None = None,
        project: str | None = None,
        parent_id: str | None = None,
        assignee: str | None = None,
        links: list[dict] | None = None,
    ) -> Issue: ...

    # Comments
    def list_comments(self, issue_id: str) -> list[Comment]: ...
    def save_comment(self, *, id: str | None = None, issue_id: str | None = None, body: str) -> Comment: ...

    # Documents
    def create_document(self, title: str, content: str, project: str | None = None) -> Document: ...
